version: '3.8'

services:

  notifyme:
    build:
      context: ./notifyme-sdk-backend/notifyme-sdk-backend-ws/target/docker
      dockerfile: Dockerfile
    image: notifyme:backend
    environment:
      TZ: Europe/Madrid
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/notifyme
      DATASOURCE_USER: notifyme
      DATASOURCE_PASS: notifyme
      DATASOURCE_SCHEMA: public
      DATASOURCE_FLYWAY_LOAD: 'false'

    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      service:

  postgres:
    image: postgres:12-alpine
    environment:
      TZ: Europe/Madrid
      POSTGRES_DB: notifyme
      POSTGRES_USER: notifyme
      POSTGRES_PASSWORD: notifyme
      POSTGRES_SCHEMA: notifyme
    volumes:
      - ./notifyme-sdk-backend/notifyme-sdk-backend-data/src/main/resources/db/migration/pgsql:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      service:
        aliases:
          - postgres

networks:
  service:
